name: T2 Workflow # name of the workflow
on: [push] # when it will run
jobs: # what it will run
 train-and-report: # job name
  runs-on: ubuntu-latest # where it will run
  steps:
  - uses: actions/checkout@v3 # pre-built step (checkout sourcecode)
  - uses: actions/setup-python@v4
  - uses: iterative/setup-cml@v1
  - uses: iterative/setup-dvc@v1
  - name: Train model
    run: | # custom commands
      pip install -r requirements.txt
      dvc pull data --run-cache
      dvc repro 